### ISSUE TITLE
v1.3 fails to run, but why?

### ISSUE THREAD

**Issue by boudiccas** [milan102/ForeverNote#1]
I've installed ForeverNote on my Debian 9 box and have totally failed in getting it to run, giving me this error message
````
./ForeverNote
Aug 12, 2017 2:00:59 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.111 by JavaFX runtime of version 8.0.60
Exception in Application start method
ForeverNote Error invoking method.
ForeverNote Failed to launch JVM
````
What do I need to get it to run please as dpkg installs it without any difficulties. and I'm now struggling with it.

Thanks
Sharon.

**Comment by milanify** [comment]
Hi,

The .deb package should work, but you can also try the jar file. 

Please download version 1.3 of the .jar file here: https://sourceforge.net/projects/forevernote/files/v1.3/ForeverNote-1.3.jar/download

Then use the command line and run the file using: java -jar "ForeverNote-1.3.jar"

See if that fixes the issue, or if you get another error let me know.

You can also update your Java

P.S. sorry about not getting to your issue sooner, I had notifications for new discussions off

**Comment by gvanto** [comment]
Hi,

I'm also getting this issue:

$ java -jar ForeverNote-1.3.jar
> Error: Could not find or load main class forevernote.Main
> Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

I have installed this:
sudo apt-get install openjfx

So desperate to get this Forevernote client working on my ubuntu (18.04 bionic)

Thanks for any help
gvanto

**Comment by milanify** [comment]
Hi,

Usually doing "sudo apt-get install openjfx" works, but not in your case.

Try the following commands below:
sudo apt-get purge openjdk*
sudo apt autoremove
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo apt install oracle-java8-set-default

If that doesn't work, try the below:

This issue comes from the way your Java is configured, might be because you have both OpenJDK 8 and OpenJDK 9 installed. Try uninstalling OpenJDK 9 and just have 8 only, see if that works.. Run "java -version" and make sure you're on version 1.8. 

Maybe try installing this, https://packages.ubuntu.com/search?keywords=openjfx (select the 3rd option for bionic)

Check this bug thread https://github.com/TomGrill/gdx-facebook/issues/40, apparently there is the "OpenJDK" version of Java and "Oracle" version of java. From what they say here you may need to install the Oracle version.

Let me know if this works for you!
